name:                log-classifier
version:             0.1.0.0
github:              "githubuser/log-classifier"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/log-classifier#readme>

dependencies:
- base >= 4.7 && < 5
- zip-archive 
- regex-tdfa 
- reflection 
- aeson 
- http-conduit
- attoparsec
- bytestring
- containers
- text
- mtl
- array

library:
  source-dirs: src

executables:
  log-classifier-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - log-classifier

tests:
  log-classifier-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - log-classifier
